// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKez6SyprmqRcE_uXu_In61hO9PV_vsdc',
    appId: '1:224556843140:web:42713be8a5d5f4ec7202d1',
    messagingSenderId: '224556843140',
    projectId: 'muslimguidance-b8fe9',
    authDomain: 'muslimguidance-b8fe9.firebaseapp.com',
    storageBucket: 'muslimguidance-b8fe9.firebasestorage.app',
    measurementId: 'G-ZVVWDGQ84B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjUM5avjhvBXCa8huQ-Y6bG4ZgYCfyhAc',
    appId: '1:224556843140:android:49481503440c20f77202d1',
    messagingSenderId: '224556843140',
    projectId: 'muslimguidance-b8fe9',
    storageBucket: 'muslimguidance-b8fe9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnKgxGJhmWZdFrV3iOwGGcR4fa_VG3sHg',
    appId: '1:224556843140:ios:7ce1a6b7ad6d96087202d1',
    messagingSenderId: '224556843140',
    projectId: 'muslimguidance-b8fe9',
    storageBucket: 'muslimguidance-b8fe9.firebasestorage.app',
    iosBundleId: 'com.muslimguidance',
  );
}
